# Documentation at https://gitlab.com/Njinx/instx#configuration

default_instance:

proxy:
  port: 8080
  preferences_url:
  faster_ddg_bangs: true

updater:
  update_interval: 180
  instance_blacklist:

  advanced:
    initial_resp_weight: 1.2
    search_resp_weight: 1.2
    google_search_resp_weight: 0.6
    wikipedia_search_resp_weight: 0.8
    outlier_multiplier: 2.0

  criteria:
    minimum_csp_grade: A
    minimum_tls_grade: A
    allowed_http_grades: [V, F, C]
    allow_analytics: no
    is_onion: no
    require_dnssec: yes
    searxng_preference: required


